# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_tuna.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_tuna.proto\x12\x04\x64\x61ta\"\x1e\n\x0cVision_color\x12\x0e\n\x06vision\x18\x01 \x01(\t\"R\n\x06\x43ounts\x12\x0b\n\x03red\x18\x01 \x01(\x05\x12\x0e\n\x06yellow\x18\x02 \x01(\x05\x12\r\n\x05green\x18\x03 \x01(\x05\x12\x0c\n\x04\x62lue\x18\x04 \x01(\x05\x12\x0e\n\x06purple\x18\x05 \x01(\x05\"\x1b\n\x0crobot1_color\x12\x0b\n\x03now\x18\x01 \x01(\t\"\x8c\x01\n\x06remain\x12\x14\n\x0cremain_line1\x18\x01 \x01(\x05\x12\x14\n\x0cremain_line2\x18\x02 \x01(\x05\x12\x14\n\x0cremain_line3\x18\x03 \x01(\x05\x12\x14\n\x0cremain_line4\x18\x04 \x01(\x05\x12\x14\n\x0cremain_line5\x18\x05 \x01(\x05\x12\x14\n\x0cremain_line6\x18\x06 \x01(\x05\"\x93\x01\n\x07maximum\x12\x15\n\rmaximum_line1\x18\x01 \x01(\x05\x12\x15\n\rmaximum_line2\x18\x02 \x01(\x05\x12\x15\n\rmaximum_line3\x18\x03 \x01(\x05\x12\x15\n\rmaximum_line4\x18\x04 \x01(\x05\x12\x15\n\rmaximum_line5\x18\x05 \x01(\x05\x12\x15\n\rmaximum_line6\x18\x06 \x01(\x05\"&\n\rrobot2_weight\x12\x15\n\rrobot2_weight\x18\x01 \x01(\x05\"&\n\rrobot3_weight\x12\x15\n\rrobot3_weight\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xc9\x02\n\x04\x44\x61ta\x12.\n\tGet_color\x12\x0b.data.Empty\x1a\x12.data.Vision_color\"\x00\x12$\n\x05\x43ount\x12\x0b.data.Empty\x1a\x0c.data.Counts\"\x00\x12\x31\n\x0cRobot1_color\x12\x0b.data.Empty\x1a\x12.data.robot1_color\"\x00\x12%\n\x06Remain\x12\x0b.data.Empty\x1a\x0c.data.remain\"\x00\x12\'\n\x07Maximum\x12\x0b.data.Empty\x1a\r.data.maximum\"\x00\x12\x33\n\rRobot2_weight\x12\x0b.data.Empty\x1a\x13.data.robot2_weight\"\x00\x12\x33\n\rRobot3_weight\x12\x0b.data.Empty\x1a\x13.data.robot3_weight\"\x00\x42*\n\x15io.grpc.examples.dataB\tDataProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_tuna_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.grpc.examples.dataB\tDataProtoP\001\242\002\003HLW'
  _globals['_VISION_COLOR']._serialized_start=25
  _globals['_VISION_COLOR']._serialized_end=55
  _globals['_COUNTS']._serialized_start=57
  _globals['_COUNTS']._serialized_end=139
  _globals['_ROBOT1_COLOR']._serialized_start=141
  _globals['_ROBOT1_COLOR']._serialized_end=168
  _globals['_REMAIN']._serialized_start=171
  _globals['_REMAIN']._serialized_end=311
  _globals['_MAXIMUM']._serialized_start=314
  _globals['_MAXIMUM']._serialized_end=461
  _globals['_ROBOT2_WEIGHT']._serialized_start=463
  _globals['_ROBOT2_WEIGHT']._serialized_end=501
  _globals['_ROBOT3_WEIGHT']._serialized_start=503
  _globals['_ROBOT3_WEIGHT']._serialized_end=541
  _globals['_EMPTY']._serialized_start=543
  _globals['_EMPTY']._serialized_end=550
  _globals['_DATA']._serialized_start=553
  _globals['_DATA']._serialized_end=882
# @@protoc_insertion_point(module_scope)
