# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
import time
import queue
import urllib.request
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import uic
from PyQt5 import QtWidgets, QtCore, QtGui


from concurrent import futures

import logging
import threading

import grpc
import grpc_tuna_pb2
import grpc_tuna_pb2_grpc
import time

Vision_ip=''
Vision_port=''

RbPi1_ip=''
RbPi1_port=''

RbPi2_ip = ''
RbPi2_port =''

Scada_ip=''


form_class = uic.loadUiType("main.ui")[0]

#화면을 띄우는데 사용되는 Class 선언
class WindowClass(QMainWindow, form_class) :
    def __init__(self) :
        super().__init__()
        self.setupUi(self)
        self.robot1_color_num=0
        self.robot2_weight=0
        self.robot3_weight=0
        self.red_count=0
        self.yellow_count=0
        self.green_count=0
        self.blue_count=0
        self.purple_count=0
        

        self.lcd_robot1.setProperty("value", self.robot1_color_num)
        self.lcd_robot2.setProperty("value", self.robot2_weight)
        self.lcd_robot3.setProperty("value", self.robot3_weight)

        self.lcd_10kg.setProperty("value", self.red_count)
        self.lcd_20kg.setProperty("value", self.yellow_count)
        self.lcd_30kg.setProperty("value", self.green_count)
        self.lcd_40kg.setProperty("value", self.blue_count)
        self.lcd_50kg.setProperty("value", self.purple_count)

        
if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = WindowClass()
    ui.show()
    sys.exit(app.exec_())

    