# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delta_System.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delta(object):
    def setupUi(self, delta):
        delta.setObjectName("delta")
        delta.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setBold(True)
        font.setWeight(75)
        delta.setFont(font)
        delta.setStyleSheet("background-color:grey;")

        self.retranslateUi(delta)
        QtCore.QMetaObject.connectSlotsByName(delta)

    def retranslateUi(self, delta):
        _translate = QtCore.QCoreApplication.translate
        delta.setWindowTitle(_translate("delta", "delta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delta = QtWidgets.QDialog()
    ui = Ui_delta()
    ui.setupUi(delta)
    delta.show()
    sys.exit(app.exec_())
